name: Deploy Dev
on:
  push:
    branches:
      - 'develop'
jobs:
  deploy-dev:
    name: Deploy Dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      NPMRC: ${{ secrets.AIRPORT_NPMRC }}
      NEXT_PUBLIC_PRISMIC_REPO: ${{ secrets.NEXT_PUBLIC_PRISMIC_REPO }}
